---

version: "2"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_PREFIX}.0/24
          gateway: ${SUBNET_PREFIX}.1

volumes:
  image_registry_cache:

services:
  repository:
    image: httpd:2.4-alpine
    networks:
      default:
        aliases: [repository.epiphany.lh]
        ipv4_address: ${SUBNET_PREFIX}.4
    ports:
      - ${REPOSITORY_PORT}:80/tcp
    volumes:
      - ${OFFLINE_DIR}/:/usr/local/apache2/htdocs/:ro
    restart: "unless-stopped"

  image_registry:
    image: registry:2
    networks:
      default:
        aliases: [image-registry.epiphany.lh]
        ipv4_address: ${SUBNET_PREFIX}.8
    ports:
      - ${IMAGE_REGISTRY_PORT}:5000/tcp
    volumes:
      - image_registry_cache:/var/lib/registry/:rw
    restart: "unless-stopped"

  skopeo_upload:
    depends_on: [image_registry]
    image: alpine:3
    networks:
      default:
        aliases: [skopeo-upload.epiphany.lh]
        ipv4_address: ${SUBNET_PREFIX}.16
    volumes:
      - ${OFFLINE_DIR}/:/offline_directory/:ro
    restart: "no"
    entrypoint: []
    command:
      - /bin/sh
      - -ec
      - >-
        : INSTALL CURL, JQ AND SKOPEO;
        apk --no-cache add curl jq skopeo;

        : WAIT FOR REGISTRY TO BECOME AVAILABLE;
        for RETRY in 9 8 7 6 5 4 3 2 1 0; do
          if curl -fsSL "http://image-registry.epiphany.lh:5000/v2/"; then
            break;
          fi;
          sleep 4;
        done && [ "$${RETRY}" -gt 0 ];

        : UPLOAD ALL IMAGES TO REGISTRY;
        jq -r '.[] | [.file_name, .name] | @tsv' /offline_directory/images_to_load.json | while IFS=$$'\t' read FILE_NAME NAME; do
          if [ -f "/offline_directory/images/$${FILE_NAME}" ]; then
            : UPLOAD CURRENT IMAGE;
            skopeo copy --quiet --dest-tls-verify=false "docker-archive:/offline_directory/images/$${FILE_NAME}" "docker://image-registry.epiphany.lh:5000/$${NAME}";
          fi;
        done;

# vim:ts=2:sw=2:et:syn=yaml:
