http:
  services:
    repository:
      loadBalancer:
        servers:
          - url: http://repository.epiphany.lh:80
    image_registry:
      loadBalancer:
        servers:
          - url: http://image-registry.epiphany.lh:5000

  routers:
    repository: &repository
      entrypoints: [web]
      rule: PathPrefix(`/epirepo`)
      service: repository
    repository_secure:
      <<: *repository
      entrypoints: [websecure]
      tls: {}

    image_registry: &image_registry
      entrypoints: [web]
      rule: PathPrefix(`/`)
      service: image_registry
    image_registry_secure:
      <<: *image_registry
      entrypoints: [websecure]
      tls: {}

tls:
  options:
    default:
      sniStrict: true
  stores:
    default:
      defaultCertificate:
        keyFile: /certificates/epiphany.lh.key.pem
        certFile: /certificates/epiphany.lh.chain.pem
