---
version: "2"

services:
  repository:
    image: epiphany-offline-repository_redhat_7
    entrypoint: []
    command:
      - /bin/bash
      - -c
      - >-
        set -o errexit -o nounset -o pipefail;

        : RUN CREATEREPOS;
        cd /usr/local/apache2/htdocs/epirepo/packages/;
        createrepo .;

        : CREATE HELM INDEX;
        cd /usr/local/apache2/htdocs/epirepo/charts/system/;
        helm repo index .;

        : RUN HTTPD;
        httpd-foreground;
